### ISSUE TITLE
HP_max field cannot be read

### ISSUE THREAD

**Issue by westonwyse** [rgould/dcc_tabbed_sheet#5]
I am using the DCC Tabbed character sheet in a campaign I am starting, and I am trying but failing to write a script that reads the value of the HP_max attribute for a selected token. `@{selected|HP_max}` always returns 1, whether I set it in the 0-level tab or the 1+ level tab. `@{selected|HP}` works as expected, returning the current HP, as do all other attributes I have used so far.

I've noticed that changes to HP_max are also not showing up in the list on the "Attributes and Abilities" tab. If I manually set a value in the Attributes list, `@{selected|HP_max}` will start returning that value, but changes to Max HP on the character sheet will not update that field. When I delete that manually-created field, `@{selected|HP_max}` goes back to returning 1.

**Comment by rgould** [comment]
@westonwyse that's weird! `HP_max` should work. You can see the definition of the attribute here: https://github.com/rgould/dcc_tabbed_sheet/blob/master/views/shared/_character_information.erb#L34

I am able to duplicate this in my own game, getting the same result. In fact, it also happens with `CritDie` and `CritDie_max`, except the latter returns "I" instead of "1". These are the default values on the Level 0 tab, declared here: https://github.com/rgould/dcc_tabbed_sheet/blob/master/views/tabs/_level0.erb#L49

Not sure how to solve this one for the moment. I am seeing that the `HP_max` attribute *does* update on the "Attributes and Abilities" tab for me. But still `@{selected|HP_max}` always returns 1.

I don't have any more time tonight, but I'll try and investigate a bit further this weekend, or find a workaround.

Thanks for posting this issue!

**Comment by rgould** [comment]
@westonwyse found a workaround. I'm not sure if it's the official preferred way to do things, but with max values, one should use `|max` instead of `_max`. So: `@{selected|HP|max}` - this works for me at least

(I'll close this assume this works for you - if not, just reopen the issue and leave a comment)

**Comment by rgould** [comment]
Also note that not all values on the character use `_max` for attributes. For example, strength is `str` and `strMax` - it's a legacy issue from when the character sheet was made that has yet to be adjusted (using `str_max` instead)

**Comment by westonwyse** [comment]
Just wanted to let you know that this works. Thank you for the update!
